### PR TITLE
Feature/resources releasing additional cases and unsubscription

### PR DESCRIPTION
**Pull request by dev-gh**
Cases are: user exits application from HMI, application is unregistered,
mobile applications are disabled by user from HMI, policy table revokes
module(s) of application.

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@dev-gh is this PR covers or supplements https://github.com/LuxoftAKutsan/sdl_core/pull/236 ?

**Comment by dev-gh** [comment]
@LuxoftAKutsan 
Covers. Includes notes fixes, bugfixes, changes regarding unsubscription during resource releasing.

**Review by LuxoftAKutsan — APPROVED** [review]

**Comment by LuxoftAKutsan** [comment]
@dev-gh #236 not actual ?

**Review by AKalinich-Luxoft — APPROVED** [review]

**Comment by dev-gh** [comment]
@LuxoftAKutsan 
Yes, its not actual, I closed it.

**Pull request merged**
